# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"label_2D": "00_core.ipynb",
         "track_3D": "00_core.ipynb",
         "mhw": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hscannell.github.io/ocetrac/"

git_url = "https://github.com/hscannell/ocetrac/tree/master/"

def custom_doc_links(name): return None
