# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_label.ipynb"}

modules = ["label.py"]

doc_url = "https://hscannell.github.io/ocetrac/"

git_url = "https://github.com/hscannell/ocetrac/tree/master/"

def custom_doc_links(name): return None
